# Generated by Django 4.1.5 on 2023-01-27 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_agerestriction_award_awardcategory_country_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='age_restriction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='viewer.agerestriction'),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='country',
        ),
        migrations.AlterField(
            model_name='movie',
            name='earnings',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='expanses',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AlterField(
            model_name='movie',
            name='images',
            field=models.ManyToManyField(blank=True, to='viewer.image'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='link',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='acting',
            field=models.ManyToManyField(blank=True, related_name='acting_in_movie', to='viewer.movie'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='artist_name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='awards',
            field=models.ManyToManyField(blank=True, to='viewer.award'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='directing',
            field=models.ManyToManyField(blank=True, related_name='directing_movie', to='viewer.movie'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='surname',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(to='viewer.country'),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='viewer.genre'),
        ),
    ]
