# Generated by Django 4.1.5 on 2023-01-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_alter_movie_released'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.ManyToManyField(related_name='movies', to='viewer.country'),
        ),
    ]
