# Generated by Django 4.1.5 on 2023-01-31 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_alter_movie_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='movies', to='viewer.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='movies', to='viewer.image'),
        ),
    ]
