# Generated by Django 4.1.5 on 2023-02-02 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0007_alter_movie_genre_alter_movie_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='awards',
            field=models.ManyToManyField(blank=True, related_name='staff', to='viewer.award'),
        ),
    ]
